### ISSUE TITLE
Is there a way to replace values of parameters in the header as, for instance, the start and end depth?

### ISSUE THREAD

**Issue by raquelsilva** [WarrenWeckesser/las#2]
I need to edit the header of the las files to change the start and end depth, the null values and, if possible, add more parameters.

Is it possible to do it with this module?

I've already tried the solution presented in other module but it didn't work properly.

**Comment by WarrenWeckesser** [comment]
> Is it possible to do it with this module?

No.  The `las` package is just a reader.  It doesn't provide any tools for editing the data or for writing LAS files.

I knew when I created it that eventually someone (probably me!) would want the ability to *write* LAS files with this package, but so far that has been a low priority for me.  There is only a limited amount of time available to work on free open-source projects, and a LAS writer has never made it to the top of my "to do" list.
